---
- name: Deploying chat_bot
  hosts: localhost
  connection: local
  tasks:
    - name: Run docker image
      docker_container:
        name: chat_bot
        image: venkata7777/chat_bot:latest
        command: python manage.py runserver 8000
        state: present
        exposed_ports:
          - 8000
